-- data entry for cateogry
SET SEARCH_PATH TO armydb;
INSERT INTO "cateogry" (name_ ,class_)VALUES('AK47','semi-automatic');
INSERT INTO "cateogry" (name_ ,class_)VALUES ('Ikbiza', 'ballistic-missile');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Agni 2', 'ballistic-missile');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Agni 3','ballistic-missile');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Agni 4','ballistic-missile');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Agni 5','ballistic-missile');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Beretta 92 A', 'Handgun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Colt M1911','semi-automatic-pistol');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Glock','semi-automatic-pistol');
INSERT INTO "cateogry" (name_ ,class_) VALUES('M14', 'rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Galil','assault rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('AK100', 'rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Barret M82', 'semi-automatic rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('SPG-9', 'recoilless-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Pistol Auto 9mm 1A','semi-automatic pistol');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Glock 17', 'pistol');
INSERT INTO "cateogry" (name_ ,class_) VALUES('SAF Carbine 1A', 'submachine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Micro Uzi','submachine-guns');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Sub-Machine Carbine','submachine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('1B1 INSAS', 'light-machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('IMI Tavor TAR-21','semi-automatic-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('AKM','assault-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Arsenal Co', 'rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('MPi-KM','assault-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Pistol Mitralier? model 1990','assault-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('AK-103','assault-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Vz-58','assault-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('MCIWS','assault-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Mauser SP66', 'sniper-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('IMI Galil 7.62 Sniper','sniper-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Heckler & Koch PSG1','semi-automatic-sniper');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Dragunov SVD59', 'semi-automatic-sniper');


INSERT INTO "cateogry" (name_ ,class_) VALUES('OSV-96','semi-automatic-sniper');
INSERT INTO "cateogry" (name_ ,class_) VALUES('M2 Browning','machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('NSV','machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('KPV','machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('INSAS LMG','light-machine-un');
INSERT INTO "cateogry" (name_ ,class_) VALUES('MG 2A1','machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('MG 5A','machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('MG 6A', 'machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('APS','underwater-rifle');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Mk 2 Machete','knife');
INSERT INTO "cateogry" (name_ ,class_) VALUES('M3 Trench Knife','knife');
INSERT INTO "cateogry" (name_ ,class_) VALUES('M4 Bayonet','knife');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Knife LC-14-B', 'knife');
INSERT INTO "cateogry" (name_ ,class_) VALUES('Excalibur','sword');
INSERT INTO "cateogry" (name_ ,class_) VALUES('PKM','machine-gun');
INSERT INTO "cateogry" (name_ ,class_) VALUES('IMI Negev','machine-gun');
