set search_path to armydb;

-- data entry for the location
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('298144','Bokaro Steel City','Jharkhand','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('189512','Port Blair','AN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('846529','Imphal','Manipur','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('730552','Bhiwani','Haryana','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('648184','Itanagar','Arunachal Pradesh','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('776890','Pali','RJ','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('671365','Panjim','GA','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('454690','Chandigarh','CH','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('991955','Silvassa','DN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('640565','Imphal','Manipur','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('498993','Gangtok','Sikkim','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('126239','Srinagar','JK','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('194103','Kargil','JK','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('185111','Poonch','JK','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('928032','Rajkot','Gujarat','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('307820','Kavaratti','Lakshadweep','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('761137','Silvassa','Dadra and Nagar Haveli','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('618987','Ongole','AP','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('623846','Gaya','Bihar','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('144790','Junagadh','GJ','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('167009','Purulia','JH','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('727545','Aizwal','MZ','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('591813','Kasur','Punjab','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('543801','Agartala','Tripura','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('446011','Pondicherry','Pondicherry','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('385496','Raurkela','Odisha','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('964318','Purnea','JH','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('733903','Junagadh','Gujarat','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('941770','Panjim','Goa','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('835438','Dehradun','UT','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('886271','Chandigarh','CH','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('663615','Rohtak','HR','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('472673','Haridwar','Uttarakhand','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('277941','Shimla','HP','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('984369','Ganganagar','Rajasthan','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('981321','Pondicherry','Pondicherry','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('706510','Kohima','Nagaland','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('817245','Haridwar','UT','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('371567','Guntakal','AP','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('001206','Dhaka','Absurd','Bangladesh'); -- Absurd means there is no significance
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('365839','Nanded','Maharastra','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('836343','Daman','DD','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('769509','Khandwa','Madhya Pradesh','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('705001','Bhubaneswar','Odisha','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('669915','Chiniot','Punjab','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('298453','Karimnagar','AP','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('568162','Port Blair','AN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('849459','Madurai','Tamil Nadu','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('354688','Panjim','GA','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('524877','Surendranagar','GJ','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('728228','Wah','PB','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('572089','Silvassa','DN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('419095','Ingraj Bazar','West Bengal','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('220096','Chandigarh','Chandigarh','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('816761','Silvassa','DN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('422081','Panjim','Goa','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('969385','Dibrugarh','Assam','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('593496','Gangtok','SK','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('953691','Kolhapur','Maharastra','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('573439','Pondicherry','Pondicherry','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('570525','Bhilai','Chhattisgarh','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('445625','Madurai','TN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('142301','Raurkela Civil Township','OR','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('918212','Shillong','Meghalaya','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('836448','Dehradun','UT','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('302913','Srinagar','Jammu and Kashmir','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('449099','Gojra','PB','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('261870','Palakkad','Kerala','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('620847','Delhi','DL','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('233002','Sheikhupura','PB','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('776198','Ganganagar','Rajasthan','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('613519','Sheikhupura','Punjab','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('176160','Kolkata','West Bengal','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('941581','Silvassa','DN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('389830','Purnea','JH','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('604377','Silvassa','DN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('289051','Dibrugarh','Assam','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('809956','Bhavnagar','GJ','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('268825','Bettiah','Bihar','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('553179','Dibrugarh','AS','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('485735','Aizwal','Mizoram','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('515605','Jamnagar','Gujarat','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('252411','Aizwal','MZ','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('555131','Panjim','Goa','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('183998','Jalna','Maharastra','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('369382','Shimla','HP','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('274780','Shillong','Meghalaya','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('616893','Shillong','ML','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('966635','Gangtok','Sikkim','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('467702','Murwara','Madhya Pradesh','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('615147','Sambalpur','OR','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('505125','Basirhat','WB','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('641879','Shimla','Himachal Pradesh','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('220038','Amravati','MH','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('683949','Purnea','Jharkhand','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('547677','Nagarcoil','TN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('783632','Agartala','TR','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('432300','Daman','DD','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('648129','Madurai','TN','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('266559','Daman','Daman and Diu','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('340320','Shillong','Meghalaya','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('715244','Nanded','Maharastra','India');
INSERT INTO "location" (PinCode,District,State,Country) VALUES ('454981','Bidar','KA','India');
