
-- data entry for Manufacturing details
SET SEARCH_PATH to armydb;
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1053,'2000-03-12','Kanpur','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1585,'2015-09-09','Lucknow','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1029,'2005-6-8','Mumbai','Bharatdynamics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharatdynamics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1366,'2003-3-2','Goa','GoaShipyard');
INSERT INTO "company" (orgName, countryname) VALUES ('Goashipyard', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1322,'2006-4-2','Goa','GoaShipyard');
INSERT INTO "company" (orgName, countryname) VALUES ('Goashipyard', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1473,'2010-7-4','Bengaluru','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1355,'2004-4-3','Hyderabad','Mishra Dhatu Nigam');
INSERT INTO "company" (orgName, countryname) VALUES ('Mishra Dhatu Nigam', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1574,'2001-5-1',' Mumbai','Mazagon Dock Shipbuilders Limited');
INSERT INTO "company" (orgName, countryname) VALUES ('Mazagon Dock Shipbuilders Limited', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1280,'2008-8-7','Bilaspur','Bharat Earth Movers');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Earth Movers', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1047,'2006-1-2','Bengaluru','Bharat Electronics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Electronics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1551,'2012-6-2','Ahmedabad','Bharat Electronics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Electronics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1469,'2011-2-11','Nagpur','Bharat Electronics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Electronics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1786,'2010-6-10','Hyderabad','Bharat Electronics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharart Electronics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1467,'2001-1-1','Ghaziabad','Bharat Electronics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharart Electronics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1513,'2002-8-7','Panchkula','Bharat Electronics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharart Electronics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1208,'2005-6-6','Hyderabad','Bharat Dynamics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharart Dynamics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1556,'2016-9-8','Kolkata','Ordnance Factories Board');
INSERT INTO "company" (orgName, countryname) VALUES ('Ordnance Factories Board', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1303,'2004-6-30','Pune','Ordnance Factories Board');
INSERT INTO "company" (orgName, countryname) VALUES ('Ordnance Factories Board', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1259,'2013-8-18','Kanpur','Ordnance Factories Board');
INSERT INTO "company" (orgName, countryname) VALUES ('Ordnance Factories Board', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1606,'2014-12-24','Tiruchirappalli','Ordnance Factories Board');
INSERT INTO "company" (orgName, countryname) VALUES ('Ordnance Factories Board', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1859,'2001-2-21','Dehradun','Ordnance Factories Board');
INSERT INTO "company" (orgName, countryname) VALUES ('Ordnance Factories Board', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1329,'2004-3-19','Ambernath','Ordnance Factories Board');
INSERT INTO "company" (orgName, countryname) VALUES ('Ordnance Factories Board', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1946,'2000-11-29','Bhusawal','Ordnance Factories Board');
INSERT INTO "company" (orgName, countryname) VALUES ('Ordnance Factories Board', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1418,'2016-4-23','Hyderabad','Bharat Dynamics');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Dynamics', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1921,'2006-10-10','Delhi','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1779,'2007-11-25','Hyderabad','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1343,'2008-2-11','Kanpur','DMSRDE');
INSERT INTO "company" (orgName, countryname) VALUES ('DMSRDE', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1622,'2005-9-18','Bengaluru','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1851,'1999-12-12','Mumbai','Tata Group');
INSERT INTO "company" (orgName, countryname) VALUES ('Tata Group', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1064,'1998-11-12',' Mumbai','Mahindra Group');
INSERT INTO "company" (orgName, countryname) VALUES ('Mahindra Group', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1247,'2003-5-10',' Mumbai','Reliance Industries Limited');
INSERT INTO "company" (orgName, countryname) VALUES ('Reliance Industries Limited', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1255,'2005-2-10','Pune','Bharat Forge');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Forge', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1270,'2006-7-8','London','Hinduja Group');
INSERT INTO "company" (orgName, countryname) VALUES ('Hinduja Group', 'United Kingdom');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1974,'2009-8-15',' Mumbai','Larsen & Toubro Limited');
INSERT INTO "company" (orgName, countryname) VALUES ('Larsen & Toubro Limited', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1557,'2002-11-11','Kanpur','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1717,'2001-3-14','Lucknow','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1997,'2014-7-7','Pune','Bharat Forge');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Forge', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1968,'2015-10-11','Bengaluru','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1462,'2006-5-2','Hyderabad','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1742,'1996-10-14','Kanpur','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1487,'1999-9-14','Hyderabad','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1610,'2004-2-12','Lucknow','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1616,'2003-4-11','Mumbai','Tata Group');
INSERT INTO "company" (orgName, countryname) VALUES ('Tata Group', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1820,'2005-5-11','Hyderabad','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1663,'2007-3-12','Pune','Bharat Forge');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Forge', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1631,'2006-6-26','Kanpur','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1525,'2001-9-11','Lucknow','HAL');
INSERT INTO "company" (orgName, countryname) VALUES ('HAL', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1150,'2004-4-3','Mumbai','Tata Group');
INSERT INTO "company" (orgName, countryname) VALUES ('Tata Group', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1828,'2008-10-10','Pune','Bharat Forge');
INSERT INTO "company" (orgName, countryname) VALUES ('Bharat Forge', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1128,'2001-7-8','Hyderabad','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1071,'2015-10-11','Hyderabad','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');
INSERT INTO "manufacturingdetails" (Serial_No, ManufaturingDate, ManufacturingLocation, orgName) VALUES (1405,'2005-1-10','Kanpur','DRDO');
INSERT INTO "company" (orgName, countryname) VALUES ('DRDO', 'INDIA');



