SET SEARCH_PATH TO armydb;
INSERT INTO "medal"(name_) VALUES ('Ashoka Chakra');
INSERT INTO "medal"(name_) VALUES ('Ati Vishisht Seva Medal');
INSERT INTO "medal"(name_) VALUES ('India Service medal');
INSERT INTO "medal"(name_) VALUES ('General Service Medal 1947');
INSERT INTO "medal"(name_) VALUES ('Indian Distinguished Service Medal');
INSERT INTO "medal"(name_) VALUES ('Indian Independence Medal');
INSERT INTO "medal"(name_) VALUES ('Indian order of Merit');
INSERT INTO "medal"(name_) VALUES ('Kirti Chakra');
INSERT INTO "medal"(name_) VALUES ('MacGregor Medal');
INSERT INTO "medal"(name_) VALUES ('Maha Vir Chakra');
INSERT INTO "medal"(name_) VALUES ('Nao Sena Medal');
INSERT INTO "medal"(name_) VALUES ('Operation Parakram Medal');
INSERT INTO "medal"(name_) VALUES ('Operation Vijay Star');
INSERT INTO "medal"(name_) VALUES ('Param Vir Chakra');
INSERT INTO "medal"(name_) VALUES ('Param Vishist Seva Medal');
INSERT INTO "medal"(name_) VALUES ('Sainya Seva Medal');
INSERT INTO "medal"(name_) VALUES ('Samanya Seva Medal');
INSERT INTO "medal"(name_) VALUES ('Sangram Medal');
INSERT INTO "medal"(name_) VALUES ('Sarvottam Yuda Seva Medal');
INSERT INTO "medal"(name_) VALUES ('Sena Medal');
INSERT INTO "medal"(name_) VALUES ('Shaurya Chakra');
INSERT INTO "medal"(name_) VALUES ('Saichen Glacier Medal');
INSERT INTO "medal"(name_) VALUES ('Uttam Yuda Seva Medal');
INSERT INTO "medal"(name_) VALUES ('Vayu Sena Medal');
INSERT INTO "medal"(name_) VALUES ('Vir Chakra');
INSERT INTO "medal"(name_) VALUES ('Vishist Seva Medal');
INSERT INTO "medal"(name_) VALUES ('Volunteer Long Service Medal for India and the Colonies');
INSERT INTO "medal"(name_) VALUES ('Volunteer Officers Decoration for India and the Colonies');
INSERT INTO "medal"(name_) VALUES ('Wound Medal(India)');
INSERT INTO "medal"(name_) VALUES ('Yuda Seva Medal');
