SET SEARCH_PATH to armydb;
INSERT INTO "work"(Type_, Salary) Values ('Soldier', '23000');
INSERT INTO "work"(Type_, Salary) Values ('Havildar', '12000');
INSERT INTO "work"(Type_, Salary) Values ('Lieutenant', '56100');
INSERT INTO "work"(Type_, Salary) Values ('Field Marshal', '250000');
INSERT INTO "work"(Type_, Salary) Values ('Lieutenant General', '225000');
INSERT INTO "work"(Type_, Salary) Values ('Major General', '144200');
INSERT INTO "work"(Type_, Salary) Values ('Brigadier', '134400');
INSERT INTO "work"(Type_, Salary) Values ('Colonel', '125700');
INSERT INTO "work"(Type_, Salary) Values ('Lieutenant Colonel', '116700');
INSERT INTO "work"(Type_, Salary) Values ('Major', '69400');
INSERT INTO "work"(Type_, Salary) Values ('Captain', '61300');
INSERT INTO "work"(Type_, Salary) Values ('Naib Subedar', '11300');
INSERT INTO "work"(Type_, Salary) Values ('Subedar Major', '21500');
INSERT INTO "work"(Type_, Salary) Values ('Sepoy', '35500');
INSERT INTO "work"(Type_, Salary) Values ('Naik', '12000');
